### ISSUE TITLE
When using Google OAuth login, no user info in hamburger menu, navbar extends past window

### ISSUE THREAD

**Issue by pkarnia** [iit-ideashop/safety-quiz#24]
User info not properly stored to session when logging in via Google OAuth (I believe).

Take a look if https://github.com/iit-ideashop/safety-quiz/blob/65d4870e76b230c5b0a781b9b2e93c18048184e0/safety-quiz/auth.py#L65-L68 is ever accessed or assigned in the OAuth flow.

![image](https://user-images.githubusercontent.com/6912671/128267998-25be5187-4392-464a-b266-3415c177663e.png)

**Comment by harshahemanth** [comment]
name and major are being stored.
![Screenshot from 2021-08-06 12-17-14](https://user-images.githubusercontent.com/22571344/128548840-1dddc26e-63ed-4ded-90c1-807464186937.png)

**Comment by pkarnia** [comment]
https://github.com/iit-ideashop/safety-quiz/commit/4a57fcdd6de286d26c720122a78c6eaeee15fee1
